export enum PermissionNamesEnum {
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_READ = 'USER_READ',
  USERS_READ = 'USERS_READ',
  USER_DELETE = 'USER_DELETE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  USER_REACTIVATE = 'USER_REACTIVATE', 

}

