export enum PermissionNamesEnum {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  READ_USER = 'READ_USER',
  READ_USERS = 'READ_USERS',
  DELETE_USER = 'DELETE_USER',
  DEACTIVATE_USER = 'DEACTIVATE_USER',
  REACTIVATE_USER = 'REACTIVATE_USER',  

}

